### ISSUE TITLE
How to troubleshoot 

### ISSUE THREAD

**Issue by xtiansimon** [christiangenco/chrome-export-history#1]
I've been using Export History each day for the past three days to export, one link at a time, my Saved bookmarks in the Digg RSS Reader. I open maybe 20 tabs at a time, export history, and repeat.

Today, export history has stopped working. I've purchased this Extension and the CSV export button is available. However, after clicking either CSV or JSON, nothing is saved. No download bar appears at the bottom of Chrome. Nothing is behaving as expected.

I redownloaded the extension. I restarted my Mac. I removed and reinstalled Chrome. I used the app Dr. Cleaner to remove old cache files.

Any other suggestions? 

OSX 10.11.6
Chrome Version 65.0.3325.162 (Official Build) (64-bit)

**Comment by christiangenco** [comment]
Sorry about that - looks like Chrome changed the way it wants extensions to download files. It's been fixed!

I'm glad you're getting use out of this! I think you should be able to open way more than 20 links at a time before exporting; Chrome History can hold a few thousand links at a time.
