### ISSUE TITLE
Add an option to import history from file

### ISSUE THREAD

**Issue by parasiteoflife** [christiangenco/chrome-export-history#2]
As per the [API documentation](https://developer.chrome.com/extensions/history) it seems that Chrome allows to add urls into the history so it is possible you could add such a feature to this extension?

**Comment by christiangenco** [comment]
Uhhhh why would you want to do that 😅

**Comment by parasiteoflife** [comment]
To put it simple, I have an script that colours visited links, those links I add them to several programs like youtube-dl and then, in this case, I start downloading them, so in order for me to not visit/open/scrap/download a url that I've already visited/opened/scraped/downloaded and, by the same logic, I've already seen/interacted/listen/etc, say from another browser or in Youtube's case from the channel were I can just copy the url without actually visiting it, I check if the link/thumbnail is coloured, if it is that means I already visited/used that url. So, the importing of urls to my browser's history is useful as all I've to do is copy the urls (which in some cases can be even more than 9000, I think I joined a bunch of sessions) into a text file and then add them to the browser's history.

This is more obvious if I just tell you that I once had Session Buddy installed on a Chrome profile, that was 2 or 3 years ago, and all I backed up in that case was the session buddy database which I imported into my current installation of Vivaldi so now I've a lot of sessions with lots of links and none of them is on my history because I didn't backed up that, that's why I need an importing option so I can import all those links that I had on all my sessions so I can acknowledge if I already visited say that vimeo/youtube video or any other site I may use which I can differentiate by the coloured text/thumbnail.

![2020-01-15_13-40-01](https://user-images.githubusercontent.com/57022988/72461426-01559300-379d-11ea-8ad4-171265a4e9c4.png)

I know this may be niche but surely it has other uses, thanks for reading.
I hope I explained myself well, English is not my native language.

**Comment by christiangenco** [comment]
Oh neat! That's a really cool project. I think it's definitely outside the scope of this plugin, but you should be able to adapt the code here reasonably easily to import instead of export.

Are you familiar with Javascript code? `popup.js` is the only file you should need to change. If not, I'd bet you could hire someone on fiverr to adapt this code for you.
